<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AssembliesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
    $assemblies = [
            // Greater Accra Region
            ['assembly_code' => 'AMA', 'name' => 'Accra Metropolitan', 'regional_code' => 'GAR'],
            ['assembly_code' => 'ADMA', 'name' => 'Adentan Municipal', 'regional_code' => 'GAR'],
            ['assembly_code' => 'ASHMA', 'name' => 'Ashaiman Municipal', 'regional_code' => 'GAR'],
            ['assembly_code' => 'GCMA', 'name' => 'Ga Central Municipal', 'regional_code' => 'GAR'],
            ['assembly_code' => 'GEMA', 'name' => 'Ga East Municipal', 'regional_code' => 'GAR'],
            ['assembly_code' => 'GNMA', 'name' => 'Ga North Municipal', 'regional_code' => 'GAR'],
            ['assembly_code' => 'GSMA', 'name' => 'Ga South Municipal', 'regional_code' => 'GAR'],
            ['assembly_code' => 'GWMA', 'name' => 'Ga West Municipal', 'regional_code' => 'GAR'],
            ['assembly_code' => 'KKMA', 'name' => 'Kpone Katamanso Municipal', 'regional_code' => 'GAR'],
            ['assembly_code' => 'LDMA', 'name' => 'La Dade Kotopon Municipal', 'regional_code' => 'GAR'],
            ['assembly_code' => 'LNMA', 'name' => 'La Nkwantanang Madina Municipal', 'regional_code' => 'GAR'],
            ['assembly_code' => 'LEKMA', 'name' => 'Ledzokuku Municipal', 'regional_code' => 'GAR'],
            ['assembly_code' => 'TMA', 'name' => 'Tema Metropolitan', 'regional_code' => 'GAR'],
            ['assembly_code' => 'OKNMA', 'name' => 'Okaikwei North Municipal', 'regional_code' => 'GAR'],
            ['assembly_code' => 'AEMA', 'name' => 'Ayawaso East Municipal', 'regional_code' => 'GAR'],
            ['assembly_code' => 'ANMA', 'name' => 'Ayawaso North Municipal', 'regional_code' => 'GAR'],
            ['assembly_code' => 'AWMA', 'name' => 'Ayawaso West Municipal', 'regional_code' => 'GAR'],
            ['assembly_code' => 'KKMA', 'name' => 'Korle Klottey Municipal', 'regional_code' => 'GAR'],
            ['assembly_code' => 'ACMA', 'name' => 'Ablekuma Central Municipal', 'regional_code' => 'GAR'],
            ['assembly_code' => 'ANMA', 'name' => 'Ablekuma North Municipal', 'regional_code' => 'GAR'],
            ['assembly_code' => 'AWMA', 'name' => 'Ablekuma West Municipal', 'regional_code' => 'GAR'],
            ['assembly_code' => 'WGMA', 'name' => 'Weija Gbawe Municipal', 'regional_code' => 'GAR'],
            ['assembly_code' => 'SODA', 'name' => 'Shai-Osudoku District', 'regional_code' => 'GAR'],
            ['assembly_code' => 'NPDA', 'name' => 'Ningo-Prampram District', 'regional_code' => 'GAR'],
            ['assembly_code' => 'AED', 'name' => 'Ada East District', 'regional_code' => 'GAR'],
            ['assembly_code' => 'AWD', 'name' => 'Ada West District', 'regional_code' => 'GAR'],

            // Ashanti Region
            ['assembly_code' => 'KMA', 'name' => 'Kumasi Metropolitan', 'regional_code' => 'AR'],
            ['assembly_code' => 'AMMA', 'name' => 'Asokore Mampong Municipal', 'regional_code' => 'AR'],
            ['assembly_code' => 'OFMA', 'name' => 'Oforikrom Municipal', 'regional_code' => 'AR'],
            ['assembly_code' => 'KWMA', 'name' => 'Kwadaso Municipal', 'regional_code' => 'AR'],
            ['assembly_code' => 'SUMA', 'name' => 'Suame Municipal', 'regional_code' => 'AR'],
            ['assembly_code' => 'OTMA', 'name' => 'Old Tafo Municipal', 'regional_code' => 'AR'],
            ['assembly_code' => 'ASKMA', 'name' => 'Asokwa Municipal', 'regional_code' => 'AR'],
            ['assembly_code' => 'EJMA', 'name' => 'Ejisu Municipal', 'regional_code' => 'AR'],
            ['assembly_code' => 'JUAM', 'name' => 'Juaben Municipal', 'regional_code' => 'AR'],
            ['assembly_code' => 'SEKUM', 'name' => 'Sekyere Kumawu District', 'regional_code' => 'AR'],
            ['assembly_code' => 'SEKAP', 'name' => 'Sekyere Afram Plains District', 'regional_code' => 'AR'],
            ['assembly_code' => 'SEE', 'name' => 'Sekyere East District', 'regional_code' => 'AR'],
            ['assembly_code' => 'SES', 'name' => 'Sekyere South District', 'regional_code' => 'AR'],
            ['assembly_code' => 'SECM', 'name' => 'Sekyere Central District', 'regional_code' => 'AR'],
            ['assembly_code' => 'MPMA', 'name' => 'Mampong Municipal', 'regional_code' => 'AR'],
            ['assembly_code' => 'EFFA', 'name' => 'Effiduase/Asokore District', 'regional_code' => 'AR'],
            ['assembly_code' => 'AFKN', 'name' => 'Afigya Kwabre North District', 'regional_code' => 'AR'],
            ['assembly_code' => 'AFKS', 'name' => 'Afigya Kwabre South District', 'regional_code' => 'AR'],
            ['assembly_code' => 'KWEM', 'name' => 'Kwabre East Municipal', 'regional_code' => 'AR'],
            ['assembly_code' => 'ATKW', 'name' => 'Atwima Kwanwoma District', 'regional_code' => 'AR'],
            ['assembly_code' => 'ATNW', 'name' => 'Atwima Nwabiagya Municipal', 'regional_code' => 'AR'],
            ['assembly_code' => 'ATMP', 'name' => 'Atwima Mponua District', 'regional_code' => 'AR'],
            ['assembly_code' => 'ATNW', 'name' => 'Atwima Nwabiagya North District', 'regional_code' => 'AR'],
            ['assembly_code' => 'ATNS', 'name' => 'Atwima Nwabiagya South District', 'regional_code' => 'AR'],
            ['assembly_code' => 'BOS', 'name' => 'Bosomtwe District', 'regional_code' => 'AR'],
            ['assembly_code' => 'BOSF', 'name' => 'Bosome Freho District', 'regional_code' => 'AR'],
            ['assembly_code' => 'BKMA', 'name' => 'Bekwai Municipal', 'regional_code' => 'AR'],
            ['assembly_code' => 'AMWE', 'name' => 'Amansie West District', 'regional_code' => 'AR'],
            ['assembly_code' => 'AMCE', 'name' => 'Amansie Central District', 'regional_code' => 'AR'],
            ['assembly_code' => 'AMSA', 'name' => 'Amansie South District', 'regional_code' => 'AR'],
            ['assembly_code' => 'OBMA', 'name' => 'Obuasi Municipal', 'regional_code' => 'AR'],
            ['assembly_code' => 'OBE', 'name' => 'Obuasi East District', 'regional_code' => 'AR'],
            ['assembly_code' => 'ADN', 'name' => 'Adansi North District', 'regional_code' => 'AR'],
            ['assembly_code' => 'ADS', 'name' => 'Adansi South District', 'regional_code' => 'AR'],
            ['assembly_code' => 'AAN', 'name' => 'Ahafo Ano North Municipal', 'regional_code' => 'AR'],
            ['assembly_code' => 'AASE', 'name' => 'Ahafo Ano South East District', 'regional_code' => 'AR'],
            ['assembly_code' => 'AASW', 'name' => 'Ahafo Ano South West District', 'regional_code' => 'AR'],

            // Western Region
            ['assembly_code' => 'STMA', 'name' => 'Sekondi-Takoradi Metropolitan', 'regional_code' => 'WR'],
            ['assembly_code' => 'EKMA', 'name' => 'Effia-Kwesimintsim Municipal', 'regional_code' => 'WR'],
            ['assembly_code' => 'TNMA', 'name' => 'Tarkwa-Nsuaem Municipal', 'regional_code' => 'WR'],
            ['assembly_code' => 'AMAM', 'name' => 'Ahanta West Municipal', 'regional_code' => 'WR'],
            ['assembly_code' => 'ENM', 'name' => 'Ellembele District', 'regional_code' => 'WR'],
            ['assembly_code' => 'NZM', 'name' => 'Nzema East Municipal', 'regional_code' => 'WR'],
            ['assembly_code' => 'JMR', 'name' => 'Jomoro District', 'regional_code' => 'WR'],
            ['assembly_code' => 'WAS', 'name' => 'Wassa Amenfi South District', 'regional_code' => 'WR'],
            ['assembly_code' => 'WAW', 'name' => 'Wassa Amenfi West Municipal', 'regional_code' => 'WR'],
            ['assembly_code' => 'WAE', 'name' => 'Wassa Amenfi East Municipal', 'regional_code' => 'WR'],
            ['assembly_code' => 'PWMA', 'name' => 'Prestea-Huni Valley Municipal', 'regional_code' => 'WR'],

            // Western North Region
            ['assembly_code' => 'ASMA', 'name' => 'Sefwi Wiawso Municipal', 'regional_code' => 'WNR'],
            ['assembly_code' => 'BHMA', 'name' => 'Bia West District', 'regional_code' => 'WNR'],
            ['assembly_code' => 'BEM', 'name' => 'Bia East District', 'regional_code' => 'WNR'],
            ['assembly_code' => 'BOM', 'name' => 'Bodi District', 'regional_code' => 'WNR'],
            ['assembly_code' => 'JUM', 'name' => 'Juaboso District', 'regional_code' => 'WNR'],
            ['assembly_code' => 'SEBM', 'name' => 'Sefwi Bodi District', 'regional_code' => 'WNR'],
            ['assembly_code' => 'AKW', 'name' => 'Aowin Municipal', 'regional_code' => 'WNR'],
            ['assembly_code' => 'SUAM', 'name' => 'Sefwi Akontombra District', 'regional_code' => 'WNR'],
            ['assembly_code' => 'WNPM', 'name' => 'Sefwi Wiawso Municipal', 'regional_code' => 'WNR'],
            ['assembly_code' => 'WFOM', 'name' => 'Sefwi Waiwso District', 'regional_code' => 'WNR'],

            // Central Region
            ['assembly_code' => 'CCMA', 'name' => 'Cape Coast Metropolitan', 'regional_code' => 'CR'],
            ['assembly_code' => 'KEAM', 'name' => 'Komenda-Edina-Eguafo-Abirem Municipal', 'regional_code' => 'CR'],
            ['assembly_code' => 'MFA', 'name' => 'Mfantseman Municipal', 'regional_code' => 'CR'],
            ['assembly_code' => 'ABM', 'name' => 'Abura-Asebu-Kwamankese District', 'regional_code' => 'CR'],
            ['assembly_code' => 'AGA', 'name' => 'Agona East District', 'regional_code' => 'CR'],
            ['assembly_code' => 'AGW', 'name' => 'Agona West Municipal', 'regional_code' => 'CR'],
            ['assembly_code' => 'ASIA', 'name' => 'Asikuma-Odoben-Brakwa District', 'regional_code' => 'CR'],
            ['assembly_code' => 'ASYM', 'name' => 'Assin South District', 'regional_code' => 'CR'],
            ['assembly_code' => 'ASYM', 'name' => 'Assin North Municipal', 'regional_code' => 'CR'],
            ['assembly_code' => 'GOM', 'name' => 'Gomoa West District', 'regional_code' => 'CR'],
            ['assembly_code' => 'GOMA', 'name' => 'Gomoa Central District', 'regional_code' => 'CR'],
            ['assembly_code' => 'GOMBA', 'name' => 'Gomoa East District', 'regional_code' => 'CR'],
            ['assembly_code' => 'AKEAM', 'name' => 'Ajumako-Enyan-Essiam District', 'regional_code' => 'CR'],
            ['assembly_code' => 'ASYM', 'name' => 'Awutu Senya East Municipal', 'regional_code' => 'CR'],
            ['assembly_code' => 'GAE', 'name' => 'Awutu Senya West District', 'regional_code' => 'CR'],
            ['assembly_code' => 'EKUM', 'name' => 'Ekumfi District', 'regional_code' => 'CR'],
            ['assembly_code' => 'EFMA', 'name' => 'Effutu Municipal', 'regional_code' => 'CR'],
            ['assembly_code' => 'HEK', 'name' => 'Heman-Lower Denkyira District', 'regional_code' => 'CR'],
            ['assembly_code' => 'KEM', 'name' => 'Komenda-Edina-Eguafo-Abirem Municipal', 'regional_code' => 'CR'],
            ['assembly_code' => 'KWA', 'name' => 'Upper Denkyira West District', 'regional_code' => 'CR'],
            ['assembly_code' => 'UKMA', 'name' => 'Upper Denkyira East Municipal', 'regional_code' => 'CR'],

            // Eastern Region
            ['assembly_code' => 'NMMA', 'name' => 'New Juaben North Municipal', 'regional_code' => 'ER'],
            ['assembly_code' => 'NEMMA', 'name' => 'New Juaben South Municipal', 'regional_code' => 'ER'],
            ['assembly_code' => 'YEMA', 'name' => 'Yilo Krobo Municipal', 'regional_code' => 'ER'],
            ['assembly_code' => 'SUEM', 'name' => 'Suhum Municipal', 'regional_code' => 'ER'],
            ['assembly_code' => 'KOEM', 'name' => 'Koforidua Municipal', 'regional_code' => 'ER'],
            ['assembly_code' => 'KWAB', 'name' => 'Kwahu Afram Plains North District', 'regional_code' => 'ER'],
            ['assembly_code' => 'SENEM', 'name' => 'Kwahu Afram Plains South District', 'regional_code' => 'ER'],
            ['assembly_code' => 'KAEM', 'name' => 'Kwahu East District', 'regional_code' => 'ER'],
            ['assembly_code' => 'KAMA', 'name' => 'Kwahu West Municipal', 'regional_code' => 'ER'],
            ['assembly_code' => 'KOMA', 'name' => 'Krachi East District', 'regional_code' => 'ER'],
            ['assembly_code' => 'KONOR', 'name' => 'Krachi Nchumuru District', 'regional_code' => 'ER'],
            ['assembly_code' => 'KROMA', 'name' => 'Krachi West District', 'regional_code' => 'ER'],
            ['assembly_code' => 'KROMA', 'name' => 'Krobo South District', 'regional_code' => 'ER'],
            ['assembly_code' => 'KROSA', 'name' => 'Krobo North District', 'regional_code' => 'ER'],
            ['assembly_code' => 'NUDOR', 'name' => 'Nudow East District', 'regional_code' => 'ER'],
            ['assembly_code' => 'NORS', 'name' => 'Nudow West District', 'regional_code' => 'ER'],
            ['assembly_code' => 'SUEMA', 'name' => 'Suhum Municipal', 'regional_code' => 'ER'],
            ['assembly_code' => 'TEMMA', 'name' => 'Tema Metropolitan', 'regional_code' => 'ER'],
            ['assembly_code' => 'KROMMA', 'name' => 'Kwahu South District', 'regional_code' => 'ER'],
            ['assembly_code' => 'AKWAMA', 'name' => 'Akwamu North District', 'regional_code' => 'ER'],
            ['assembly_code' => 'NORKAMA', 'name' => 'North Krobo District', 'regional_code' => 'ER'],

            // Volta Region
            ['assembly_code' => 'HO', 'name' => 'Ho Municipal', 'regional_code' => 'VR'],
            ['assembly_code' => 'KEAM', 'name' => 'Keta Municipal', 'regional_code' => 'VR'],
            ['assembly_code' => 'ANOM', 'name' => 'Anloga District', 'regional_code' => 'VR'],
            ['assembly_code' => 'AKAM', 'name' => 'Akatsi North District', 'regional_code' => 'VR'],
            ['assembly_code' => 'AKAS', 'name' => 'Akatsi South District', 'regional_code' => 'VR'],
            ['assembly_code' => 'AGOM', 'name' => 'Agotime Ziope District', 'regional_code' => 'VR'],
            ['assembly_code' => 'ADAM', 'name' => 'Adaklu District', 'regional_code' => 'VR'],
            ['assembly_code' => 'AKAM', 'name' => 'Afadjato South District', 'regional_code' => 'VR'],
            ['assembly_code' => 'HOMA', 'name' => 'Hohoe Municipal', 'regional_code' => 'VR'],
            ['assembly_code' => 'BOMA', 'name' => 'Kpando Municipal', 'regional_code' => 'VR'],
            ['assembly_code' => 'DROM', 'name' => 'North Dayi District', 'regional_code' => 'VR'],
            ['assembly_code' => 'SOMA', 'name' => 'South Dayi District', 'regional_code' => 'VR'],
            ['assembly_code' => 'HOMA', 'name' => 'Hohoe Municipal', 'regional_code' => 'VR'],
            ['assembly_code' => 'DROM', 'name' => 'North Dayi District', 'regional_code' => 'VR'],
            ['assembly_code' => 'SOMA', 'name' => 'South Dayi District', 'regional_code' => 'VR'],
            ['assembly_code' => 'AWOM', 'name' => 'Afadjato South District', 'regional_code' => 'VR'],
            ['assembly_code' => 'KRAMA', 'name' => 'Krachi East Municipal', 'regional_code' => 'VR'],
            ['assembly_code' => 'KRAMU', 'name' => 'Krachi West Municipal', 'regional_code' => 'VR'],
            ['assembly_code' => 'KRAMS', 'name' => 'Krachi Nchumuru District', 'regional_code' => 'VR'],
            ['assembly_code' => 'KRAMS', 'name' => 'Krachi South District', 'regional_code' => 'VR'],

            // Oti Region
            ['assembly_code' => 'KRMMA', 'name' => 'Krachi Nchumuru District', 'regional_code' => 'OTR'],
            ['assembly_code' => 'KRSMA', 'name' => 'Krachi West Municipal', 'regional_code' => 'OTR'],
            ['assembly_code' => 'NKR', 'name' => 'Nkwanta North District', 'regional_code' => 'OTR'],
            ['assembly_code' => 'NKRS', 'name' => 'Nkwanta South Municipal', 'regional_code' => 'OTR'],
            ['assembly_code' => 'KRCHS', 'name' => 'Krachi East District', 'regional_code' => 'OTR'],
            ['assembly_code' => 'KRSS', 'name' => 'Krachi South District', 'regional_code' => 'OTR'],

            // Northern Region
            ['assembly_code' => 'TAMA', 'name' => 'Tamale Metropolitan', 'regional_code' => 'NR'],
            ['assembly_code' => 'SAKA', 'name' => 'Sagnarigu Municipal', 'regional_code' => 'NR'],
            ['assembly_code' => 'SAB', 'name' => 'Savelugu Municipal', 'regional_code' => 'NR'],
            ['assembly_code' => 'NAN', 'name' => 'Nanton District', 'regional_code' => 'NR'],
            ['assembly_code' => 'KAR', 'name' => 'Karaga District', 'regional_code' => 'NR'],
            ['assembly_code' => 'KUGU', 'name' => 'Kumbungu District', 'regional_code' => 'NR'],
            ['assembly_code' => 'GUSA', 'name' => 'Gushegu Municipal', 'regional_code' => 'NR'],
            ['assembly_code' => 'TOL', 'name' => 'Tolon District', 'regional_code' => 'NR'],
            ['assembly_code' => 'BUP', 'name' => 'Bole District', 'regional_code' => 'NR'],
            ['assembly_code' => 'DAB', 'name' => 'Daboya/Mankarigu District', 'regional_code' => 'NR'],
            ['assembly_code' => 'KPS', 'name' => 'Kpandai District', 'regional_code' => 'NR'],
            ['assembly_code' => 'BIM', 'name' => 'Bimbilla District', 'regional_code' => 'NR'],
            ['assembly_code' => 'SAL', 'name' => 'Salaga District', 'regional_code' => 'NR'],
            ['assembly_code' => 'WUL', 'name' => 'Wulensi District', 'regional_code' => 'NR'],
            ['assembly_code' => 'TAM', 'name' => 'Tamale Municipal', 'regional_code' => 'NR'],
            ['assembly_code' => 'ZAB', 'name' => 'Zabzugu District', 'regional_code' => 'NR'],
            ['assembly_code' => 'CHA', 'name' => 'Chereponi District', 'regional_code' => 'NR'],
            ['assembly_code' => 'SAB', 'name' => 'Saboba District', 'regional_code' => 'NR'],
            ['assembly_code' => 'SAH', 'name' => 'Sawla-Tuna-Kalba District', 'regional_code' => 'NR'],
            ['assembly_code' => 'YEND', 'name' => 'Yendi Municipal', 'regional_code' => 'NR'],
            ['assembly_code' => 'MION', 'name' => 'Mion District', 'regional_code' => 'NR'],

            // North East Region
            ['assembly_code' => 'NEMA', 'name' => 'Nalerigu Municipal', 'regional_code' => 'NER'],
            ['assembly_code' => 'BMMA', 'name' => 'Bunkpurugu Municipal', 'regional_code' => 'NER'],
            ['assembly_code' => 'YEMA', 'name' => 'Yemeso District', 'regional_code' => 'NER'],
            ['assembly_code' => 'GAMMA', 'name' => 'Gambaga District', 'regional_code' => 'NER'],
            ['assembly_code' => 'BIMMA', 'name' => 'Bimoba District', 'regional_code' => 'NER'],
            ['assembly_code' => 'WULMA', 'name' => 'Wulugu District', 'regional_code' => 'NER'],

            // Savannah Region
            ['assembly_code' => 'DMMA', 'name' => 'Damongo Municipal', 'regional_code' => 'SR'],
            ['assembly_code' => 'BMW', 'name' => 'Bole District', 'regional_code' => 'SR'],
            ['assembly_code' => 'EFB', 'name' => 'East Gonja District', 'regional_code' => 'SR'],
            ['assembly_code' => 'EWG', 'name' => 'East Gonja Municipal', 'regional_code' => 'SR'],
            ['assembly_code' => 'WGON', 'name' => 'West Gonja District', 'regional_code' => 'SR'],
            ['assembly_code' => 'WGM', 'name' => 'West Gonja Municipal', 'regional_code' => 'SR'],
            ['assembly_code' => 'SNTK', 'name' => 'Sawla-Tuna-Kalba District', 'regional_code' => 'SR'],
            ['assembly_code' => 'SNTKM', 'name' => 'Sawla-Tuna-Kalba Municipal', 'regional_code' => 'SR'],
            ['assembly_code' => 'NOR', 'name' => 'North Gonja District', 'regional_code' => 'SR'],
            ['assembly_code' => 'NOR', 'name' => 'North Gonja Municipal', 'regional_code' => 'SR'],

            // Upper East Region
            ['assembly_code' => 'BMA', 'name' => 'Bolgatanga Municipal', 'regional_code' => 'UER'],
            ['assembly_code' => 'BMM', 'name' => 'Bongo District', 'regional_code' => 'UER'],
            ['assembly_code' => 'BAK', 'name' => 'Bawku Municipal', 'regional_code' => 'UER'],
            ['assembly_code' => 'BAP', 'name' => 'Bawku West District', 'regional_code' => 'UER'],
            ['assembly_code' => 'TAE', 'name' => 'Talensi District', 'regional_code' => 'UER'],
            ['assembly_code' => 'TAE', 'name' => 'Tano South District', 'regional_code' => 'UER'],
            ['assembly_code' => 'TA', 'name' => 'Tano South Municipal', 'regional_code' => 'UER'],
            ['assembly_code' => 'TA', 'name' => 'Tano South District', 'regional_code' => 'UER'],
            ['assembly_code' => 'TA', 'name' => 'Tano South Municipal', 'regional_code' => 'UER'],

            // Upper West Region
            ['assembly_code' => 'WMA', 'name' => 'Wa Municipal', 'regional_code' => 'UWR'],
            ['assembly_code' => 'DWA', 'name' => 'Daffiama Bussie Issa District', 'regional_code' => 'UWR'],
            ['assembly_code' => 'JAM', 'name' => 'Jirapa Municipal', 'regional_code' => 'UWR'],
            ['assembly_code' => 'LAM', 'name' => 'Lambussie District', 'regional_code' => 'UWR'],
            ['assembly_code' => 'LUOM', 'name' => 'Lawra Municipal', 'regional_code' => 'UWR'],
            ['assembly_code' => 'NAD', 'name' => 'Nadowli Kaleo District', 'regional_code' => 'UWR'],
            ['assembly_code' => 'NAD', 'name' => 'Nadowli Kaleo Municipal', 'regional_code' => 'UWR'],
            ['assembly_code' => 'NEWM', 'name' => 'Nandom District', 'regional_code' => 'UWR'],
            ['assembly_code' => 'WEWM', 'name' => 'Wechiau District', 'regional_code' => 'UWR'],
            ['assembly_code' => 'WEWM', 'name' => 'Wechiau Municipal', 'regional_code' => 'UWR'],
        ];

          DB::table('assemblies')->insert($assemblies);
    }
}